name: Deploy to Ecs
on:
    push:
      branches:
        main
    workflow_dispatch:
jobs:
   builddeploytoecs:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: checkout code from repo
          uses: actions/checkout@v3
        - name: setup java and maven enviroment
          uses: actions/setup-java@v3
          with: 
            distribution: 'adopt'
            java-version: '11'
        - name: package with maven
          run: mvn package
        - name: code analysis with sonarqube
          run: mvn sonar:sonar -Dsonar.projectKey=xashy-webapp -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Donar.token=${{secrets.SONAR_LOGIN_TOKEN}}
        - name: upload to github packages
          run: mvn --batch-mode deploy
          env:
            githUB_TOKEN: ${{secrets.GITHUB_TOKEN}}